name = "sage-api"
main = "src/worker.js"
compatibility_date = "2026-06-14"
workers_dev = false
account_id = "615b5d24ac380d486fb5873d2faadd05"

[[routes]]
pattern = "sage.api.marketingstudios.in"
custom_domain = true

[[kv_namespaces]]
binding = "SAGE_PROOF"
id = "82f187dbd5304cc5bc06a3d2f49be707"
