name = "psyc-god-sage-api"
main = "src/worker.js"
compatibility_date = "2026-06-14"
workers_dev = true
account_id = "18aecc3a0dcb9092bdf98be9cb21bd7a"

[[d1_databases]]
binding = "DB"
database_name = "sage_telemetry"
database_id = "2483de7b-ad2a-4f86-93d2-d2b7635f79ac"

[[queues.producers]]
binding = "TELEMETRY_QUEUE"
queue = "sage-telemetry-queue"
